#define COMPONENT support
#define COMPONENT_BEAUTIFIED Support
#include "\z\a3cs\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#include "\z\a3cs\addons\main\script_macros.hpp"

#define IDC_RSCSUPPORTPANEL_TITLEBG 2080
#define IDC_RSCSUPPORTPANEL_ASSETTITLE 2081
#define IDC_RSCSUPPORTPANEL_MAINBG 2082
#define IDC_RSCSUPPORTPANEL_TITLE 2083
#define IDC_RSCSUPPORTPANEL_ASSETS 2084
#define IDC_RSCSUPPORTPANEL_PROPERTIES 2085
#define IDC_RSCSUPPORTPANEL_MAP 2086
#define IDC_RSCSUPPORTPANEL_BUTTONSEND 2087
