#define COMPONENT nametags
#define COMPONENT_BEAUTIFIED Name Tags
#include "\z\a3cs\addons\main\script_mod.hpp"

// #define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#include "\z\a3cs\addons\main\script_macros.hpp"

#define NAMETAG_2D_MAX_DISTANCE 4.5
#define NAMETAG_2D_MAX_DISTANCE_UNCONSCIOUS 2.5
#define NAMETAG_2D_FADE_IN 0.3
#define NAMETAG_2D_INIT_FADE_OUT 3600
#define NAMETAG_2D_FADE_OUT 1
#define NAMETAG_2D_NAME_SIZE 1.3
#define NAMETAG_2D_RANK_SIZE 1.05
#define NAMETAG_2D_FONT RobotoCondensed

#define NAMETAG_3D_MAX_DISTANCE 12
#define NAMETAG_3D_MAX_DISTANCE_UNCONSCIOUS 2.5
#define NAMETAG_3D_HEIGHT_DISTANCE_FACTOR 0.032
#define NAMETAG_3D_TEXT_DISTANCE_FACTOR 0.001
#define NAMETAG_3D_TEXT_HEIGHT_DISTANCE_FACTOR 0.016
#define NAMETAG_3D_HEIGHT_OFFSET 0.35
#define NAMETAG_3D_NAME_SIZE_BASE 0.068
#define NAMETAG_3D_RANK_SIZE_BASE 0.04
#define NAMETAG_3D_ICON_SIZE 1
#define NAMETAG_3D_FONT "RobotoCondensed"
#define NAMETAG_3D_TEXT_MARGIN 0.3
