/* A3 Modules */

class ModuleRadio_F: Module_F {scope = 1;};
class ModuleEffectsBubbles_F: Module_F {scope = 1;};
class ModuleEffectsShells_F: Module_F {scope = 1;};
class ModuleChemlight_F: Module_F {scope = 1;};
class ModuleCAS_F: Module_F {scope = 1;};
class ModuleEffectsFire_F: Module_F {scope = 1;};
class ModuleFlare_F: Module_F {scope = 1;};
class ModuleIRGrenade_F: Module_F {scope = 1;};
class ModuleOrdnance_F: Module_F {scope = 1;};
class ModuleEffectsPlankton_F: Module_F {scope = 1;};
class ModuleEffectsSmoke_F: Module_F {scope = 1;};
class ModuleSmoke_F: Module_F {scope = 1;};
class ModuleTracers_F: Module_F {scope = 1;};
class ModuleDate_F: Module_F {scope = 1;};
class ModuleGenericRadio_F: Module_F {scope = 1;};
class ModuleChat_F: Module_F {scope = 1;};
class ModuleSaveGame_F: Module_F {scope = 1;};
class ModuleVolume_F: Module_F {scope = 1;};
class ModuleMPTypeDefense_F: Module_F {scope = 1;};
class ModuleMPTypeGameMaster_F: Module_F {scope = 1;};
class ModuleMPTypeSectorControl_F: Module_F {scope = 1;};
class ModuleMPTypeSeize_F: Module_F {scope = 1;};
class ModuleMPTypeGroundSupport_F: Module_F {scope = 1;};
class ModuleMPTypeGroundSupportBase_F: Module_F {scope = 1;};
class ModuleCombatGetIn: Module_F {scope = 1;};
class ModuleGroupID: Module_F {scope = 1;};
class ModuleCreateDiaryRecord_F: Module_F {scope = 1;};
class ModuleTaskCreate_F: Module_F {scope = 1;};
class ModuleHQ_F: Module_F {scope = 1;};
class ModuleTaskSetDescription_F: Module_F {scope = 1;};
class ModuleTaskSetDestination_F: Module_F {scope = 1;};
class ModuleTaskSetState_F: Module_F {scope = 1;};
class ModuleAnimals_F: Module_F {scope = 1;};
class ModuleCoverMap_F: Module_F {scope = 1;};
class ModuleRadioChannelCreate_F: Module_F {scope = 1;};
class ModuleFriendlyFire_F: Module_F {scope = 1;};
class HighCommand: Module_F {scope = 1;};
class HighCommandSubordinate: Module_F {scope = 1;};
class ModuleLiveFeedEffects_F: Module_F {scope = 1;};
class ModuleLiveFeedInit_F: Module_F {scope = 1;};
class ModuleLiveFeedSetSource_F: Module_F {scope = 1;};
class ModuleLiveFeedSetTarget_F: Module_F {scope = 1;};
class ModuleLiveFeedTerminate_F: Module_F {scope = 1;};
class MartaManage: Module_F {scope = 1;};
class ModulePoster_F: Module_F {scope = 1;};
class ModuleSkirmishTrigger_F: Module_F {scope = 1;};
class ModuleSlingload_F: Module_F {scope = 1;};
class ModuleSpawnAI_F: Module_F {scope = 1;};
class ModuleSpawnAIOptions_F: Module_F {scope = 1;};
class ModuleSpawnAISectorTactic_F: Module_F {scope = 1;};
class ModuleSpawnAIPoint_F: Module_F {scope = 1;};
class ModuleTrident_F: Module_F {scope = 1;};
class ModuleCuratorUnlockArea_F: Module_F {scope = 1;};
class ModuleCuratorUnlockObject_F: Module_F {scope = 1;};
class ModuleZoneRestriction_F: Module_F {scope = 1;};
class ModuleRespawnPosition_F: Module_F {scope = 1;};
class ModuleSector_F: Module_F {scope = 1;};
class ModuleSectorDummy_F: Module_F {scope = 1;};
class ModuleRespawnVehicle_F: Module_F {scope = 1;};
class ModuleRating_F: Module_F {scope = 1;};
class ModuleDoorOpen_F: Module_F {scope = 1;};
class ModuleAI_F: Module_F {scope = 1;};
class ModuleAmmo_F: Module_F {scope = 1;};
class ModuleMode_F: Module_F {scope = 1;};
class ModulePositioning_F: Module_F {scope = 1;};
class ModuleRank_F: Module_F {scope = 1;};
class ModuleSkill_F: Module_F {scope = 1;};
class ModuleDamage_F: Module_F {scope = 1;};
class ModuleFuel_F: Module_F {scope = 1;};
class ModuleShowHide_F: Module_F {scope = 1;};
class ModuleSimulationManager_F: Module_F {scope = 1;};
class ModuleObjectiveRaceCP_F: Module_F {scope = 1;};
class ModuleObjectiveRaceFinish_F: Module_F {scope = 1;};
class ModuleObjectiveRaceStart_F: Module_F {scope = 1;};
class ModuleBleedTickets_F: Module_F {scope = 1;};
class ModuleZoneProtection_F: Module_F {scope = 1;};
class ModuleHealth_F: Module_F {scope = 1;};
class Site_Ambient: Module_F {scope = 1;};
class Site_BLUFOR: Module_F {scope = 1;};
class Site_Empty: Module_F {scope = 1;};
class Site_Independent: Module_F {scope = 1;};
class Site_Minefield: Module_F {scope = 1;};
class Site_OPFOR: Module_F {scope = 1;};
class Site_Patrol: Module_F {scope = 1;};
class ModuleStrategicMapImage_F: Module_F {scope = 1;};
class ModuleStrategicMapMission_F: Module_F {scope = 1;};
class ModuleStrategicMapModuleOpen_F: Module_F {scope = 1;};
class ModuleStrategicMapORBAT_F: Module_F {scope = 1;};
class ModuleStrategicMapInit_F: Module_F {scope = 1;};
class SupportProvider_Artillery: Module_F {scope = 1;};
class SupportProvider_Virtual_Artillery: Module_F {scope = 1;};
class SupportProvider_CAS_Bombing: Module_F {scope = 1;};
class SupportProvider_Virtual_CAS_Bombing: Module_F {scope = 1;};
class SupportProvider_CAS_Heli: Module_F {scope = 1;};
class SupportProvider_Virtual_CAS_Heli: Module_F {scope = 1;};
class SupportProvider_Transport: Module_F {scope = 1;};
class SupportProvider_Virtual_Transport: Module_F {scope = 1;};
class SupportProvider_Drop: Module_F {scope = 1;};
class SupportProvider_Virtual_Drop: Module_F {scope = 1;};
class SupportRequester: Module_F {scope = 1;};
class MartaManager: Module_F {scope = 1;};
class ModuleHvtEndGameObjective_F: Module_F {scope = 1;};
class ModuleHvtObjectivesInstance_F: Module_F {scope = 1;};
class ModuleHvtSimpleObjective_F: Module_F {scope = 1;};
class ModuleHvtStartGameObjective_F: Module_F {scope = 1;};
class ModuleCuratorAddCameraArea_F: Module_F {scope = 1;};
class ModuleCuratorAddEditableObjects: Module_F {scope = 1;};
class ModuleCuratorAddEditingArea_F: Module_F {scope = 1;};
class ModuleCuratorAddIcon_F: Module_F {scope = 1;};
class ModuleCuratorAddAddons_F: Module_F {scope = 1;};
class ModuleCuratorAddPoints_F: Module_F {scope = 1;};
class ModuleCuratorAddEditingAreaPlayers_F: Module_F {scope = 1;};
class ModuleCuratorSetAttributesGroup_F: Module_F {scope = 1;};
class ModuleCuratorSetAttributesMarker_F: Module_F {scope = 1;};
class ModuleCuratorSetAttributesObject_F: Module_F {scope = 1;};
class ModuleCuratorSetAttributesPlayer_F: Module_F {scope = 1;};
class ModuleCuratorSetAttributesWaypoint_F: Module_F {scope = 1;};
class ModuleCuratorSetCamera_F: Module_F {scope = 1;};
class ModuleCuratorSetDefaultCosts_F: Module_F {scope = 1;};
class ModuleCuratorSetSideCosts_F: Module_F {scope = 1;};
class ModuleCuratorSetModuleCosts_F: Module_F {scope = 1;};
class ModuleCuratorSetObjectCosts_F: Module_F {scope = 1;};
class ModuleCuratorSetCosts_F: Module_F {scope = 1;};
class ModuleCuratorSetEditingAreaType_F: Module_F {scope = 1;};
class ModuleCuratorSetCoefs_F: Module_F {scope = 1;};

/* Curator Modules */

class ModulePostprocess_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleLightning_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleSkiptime_F: Module_F {scope = 1;scopeCurator = 2;};
class ModuleWeather_F: Module_F {scope = 1;scopeCurator = 2;};
class ModuleTimeMultiplier_F: Module_F {scope = 1;scopeCurator = 2;};
class ModuleRespawnInventory_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleRespawnPositionWest_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleRespawnPositionEast_F: ModuleRespawnPositionWest_F {scope = 1;scopeCurator = 0;};
class ModuleRespawnPositionGuer_F: ModuleRespawnPositionWest_F {scope = 1;scopeCurator = 0;};
class ModuleRespawnPositionCiv_F: ModuleRespawnPositionWest_F {scope = 1;scopeCurator = 0;};
class ModuleVehicleRespawnPositionWest_F: ModuleRespawnPositionWest_F {scope = 1;scopeCurator = 0;};
class ModuleVehicleRespawnPositionEast_F: ModuleVehicleRespawnPositionWest_F {scope = 1;scopeCurator = 0;};
class ModuleVehicleRespawnPositionGuer_F: ModuleVehicleRespawnPositionWest_F {scope = 1;scopeCurator = 0;};
class ModuleVehicleRespawnPositionCiv_F: ModuleVehicleRespawnPositionWest_F {scope = 1;scopeCurator = 0;};
class ModuleObjective_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleObjectiveMove_F: ModuleObjective_F {scope = 1;scopeCurator = 0;};
class ModuleObjectiveSector_F: ModuleObjective_F {scope = 1;scopeCurator = 0;};
class ModuleObjectiveAttackDefend_F: ModuleObjective_F {scope = 1;scopeCurator = 0;};
class ModuleObjectiveNeutralize_F: ModuleObjective_F {scope = 1;scopeCurator = 0;};
class ModuleObjectiveProtect_F: ModuleObjective_F {scope = 1;scopeCurator = 0;};
class ModuleObjectiveGetIn_F: ModuleObjective_F {scope = 1;scopeCurator = 0;};
class ModuleBootcampStage_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleHint_F: ModuleBootcampStage_F {scope = 1;scopeCurator = 0;};
class ModulePunishment_F: ModuleBootcampStage_F {scope = 1;scopeCurator = 0;};
class ModuleCountdown_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleEndMission_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleRespawnTickets_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleMissionName_F: Module_F {scope = 1;scopeCurator = 0;};
class ModuleDiary_F: Module_F {scope = 1;scopeCurator = 0;};

/* CBA Modules */

class CBA_main_require: Module_F {scope = 1;};
class SLX_XEH_Logic: Module_F {scope = 1;};

/* ACE3 Modules */

class ACE_moduleAllowConfigExport: ACE_Module {scope = 1;};
class ACE_ModuleBlueForceTracking: ACE_Module {scope = 1;};
class ace_captives_moduleSettings: ACE_Module {scope = 1;};
class ACE_ModuleCheckPBOs: ACE_Module {scope = 1;};
class ACE_ModuleExplosive: ACE_Module {scope = 1;};
class ACE_ModuleFriendlyFire: ACE_Module {scope = 1;};
class ACE_ModuleInteraction: ACE_Module {scope = 1;};
class ACE_ModuleLSDVehicles: ACE_Module {scope = 1;};
class ACE_ModuleMap: ACE_Module {scope = 1;};
class ace_microdagr_dagrModule: ACE_Module {scope = 1;};
class ace_mk6mortar_module: ACE_Module {scope = 1;};
class ACE_ModuleRallypoint: ACE_Module {scope = 1;};
class ACE_ModuleRespawn: ACE_Module {scope = 1;};
class ACE_ModuleSwitchUnits: ACE_Module {scope = 1;};
class ACE_moduleAdvancedMedicalSettings: ACE_Module {scope = 1;};
class ACE_moduleMedicalSettings: ACE_Module {scope = 1;};
class ACE_moduleReviveSettings: ACE_Module {scope = 1;};
class ACE_moduleAssignMedicRoles: ACE_Module {scope = 1;};
class ACE_moduleAssignMedicalFacility: ACE_Module {scope = 1;};
class ACE_moduleAssignMedicVehicle: ACE_Module {scope = 1;};
class ACE_moduleAmbianceSound: ACE_Module {scope = 1;};
class ace_viewdistance_ModuleSettings: ACE_Module {scope = 1;};
class ACE_ModuleSitting: ACE_Module {scope = 1;};
class ace_captives_ModuleSurrender: Module_F {scope = 1;};
class ace_finger_moduleSettings: ACE_Module {scope = 1;};
class ace_spectator_moduleSettings: ACE_Module {scope = 1;};
class ACE_VehicleLock_ModuleSyncedAssign: ACE_Module {scope = 1;};
class ACE_VehicleLock_ModuleSetup: ACE_Module {scope = 1;};
class ace_zeus_moduleSettings: ACE_Module {scope = 1;};
class ACE_moduleAddSpareParts: Module_F {scope = 1;};
class ACE_moduleCargoSettings: ACE_Module {scope = 1;};
class ACE_moduleRepairSettings: ACE_Module {scope = 1;};
class ACE_moduleMedicalMenuSettings: ACE_Module {scope = 1;};
class ace_slideshow_module: ACE_Module {scope = 1;};
class ACE_moduleAssignEngineerRoles: Module_F {scope = 1;};
class ACE_moduleAssignRepairFacility: ACE_moduleAssignEngineerRoles {scope = 1;};
class ACE_moduleAssignRepairVehicle: Module_F {scope = 1;};
class ace_map_gestures_moduleSettings: ACE_Module {scope = 1;};
class ace_map_gestures_moduleGroupSettings: ACE_Module {scope = 1;};
class ACE_moduleRearmSettings: ACE_Module {scope = 1;};
class ACE_moduleRefuelSettings: ACE_Module {scope = 1;};
class ace_captives_ModuleHandcuffed: ACE_Module {scope = 1;};
class ace_nightvision_ModuleSettings: ACE_Module {scope = 1;};
class ace_cargo_makeLoadable: ACE_Module {scope = 1;};
class ACE_moduleBasicMedicalSettings: ACE_Module {scope = 1;};
class ACE_moduleEquipFRIES: ACE_Module {scope = 1;};
class ace_ui_Module: ACE_Module {scope = 1;};
