class RedLaserEffect {
    class RedLaser {
        simulation = "light";
        type = "Light_RedLaser";
        position[] = {0,0,0};
        intensity = 0;
        interval = 1;
        lifeTime = 6;
    };
};
class LaserCraterSmall {
    class ExploAmmoStones {
        simulation = "particles";
        type = "DirtSmall";
        position[] = {0,0,0};
        intensity = 0.3;
        interval = 0;
        lifeTime = 0.5;
    };
};
class LaserExploSmall {
    class FiredLightSmall {
        simulation = "light";
        type = "FiredLightSmall";
        position[] = {0,0,0};
        intensity = 0;
        interval = 1;
        lifeTime = 0.1;
    };
    class LaserSparks_small {
        simulation = "particles";
        type = "LaserSparks_small";
        position[] = {0,0,0};
        intensity = 5;
        interval = 1;
        lifeTime = 1;
    };
    class LaserSparks_small2 {
        simulation = "particles";
        type = "LaserSparks_small2";
        position[] = {0,0,0};
        intensity = 5;
        interval = 1;
        lifeTime = 1;
    };
    class LazerFlash {
        simulation = "particles";
        type = "LazerFlash";
        position[] = {0,0,0};
        intensity = 50;
        interval = 1;
        lifeTime = 1;
    };
    class SmallSmoke1 {
        simulation = "particles";
        type = "SmallLazerSmoke";
        position[] = {0,0,0};
        intensity = 1;
        interval = 1;
        lifeTime = 1;
    };
    class ImpactSparksSabot007 {
        simulation = "particles";
        type = "ImpactSparksSabot007";
        position[] = {0,0,0};
        intensity = 5;
        interval = 1;
        lifeTime = 1;
    };
};
class CfgSoundEffects {
    class WeaponsEffects {
        class Default;
        class DefaultDMRLaser {
            class Begin: Default{};
            class Middle: Default {
                distance = 100;
                frequency = 0.9;
                gain[] = {1,1,0.39810717,0.25118864};
                threshold = 0.1;
                ratio = 0.1;
                attack = 0;
            };
            class End: Default {
                distance = 200;
                frequency = 0.85;
                gain[] = {1,0.56234133,0.12589253,0.12589253};
                threshold = 0.1;
                ratio = 0.1;
                attack = 0;
            };
        };
    };
};
class CfgCloudlets {
    class Default {
        interval = "0.5 * interval + 0.5";
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        particleShape = "";
        particleFSNtieth = 1;
        particleFSIndex = 0;
        particleFSFrameCount = 1;
        particleFSLoop = 1;
        angle = 0;
        angleVar = 0;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 1;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 1;
        weight = 1;
        volume = 1;
        rubbing = 0.05;
        size[] = {1,1};
        color[] = {{ 1,1,1,1 }};
        animationSpeed[] = {1};
        randomDirectionPeriod = 0;
        randomDirectionIntensity = 0;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 0;
        positionVar[] = {0,0,0};
        MoveVelocityVar[] = {0,0,0};
        rotationVelocityVar = 0;
        sizeVar = 0;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class LaserSparks_small: Default {
        interval = 0.0005;
        //particleShape = "BH_SWIA_Weapons\Effects\ParticleEffects\Sparks\Sparkssmall2.p3d";
        particleShape = "\A3\data_f\ParticleEffects\Universal\smoke";
        particleFSNtieth = 1;
        particleFSIndex = 0;
        particleFSFrameCount = 1;
        particleFSLoop = 0;
        angle = 0;
        angleVar = 0;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.015;
        moveVelocity[] = {0,4,0};
        rotationVelocity = 0;
        weight = 100;
        volume = 20;
        rubbing = 0;
        size[] = {0,0.015,0.015,0}; //size[] = {0,0.085,0.085,0};
        sizeCoef = 1;
        color[] = {{ 0.7,0.7,0.7,-10 }};
        colorCoef[] = {1,1,1,1};
        animationSpeed[] = {1};
        animationSpeedCoef = 1;
        randomDirectionPeriod = 10;
        randomDirectionIntensity = 1;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 0.2;
        positionVar[] = {0,0,0};
        moveVelocityVar[] = {4,0.1,4};
        rotationVelocityVar = 0;
        sizeVar = 0.15;
        colorVar[] = {0.05,0.05,0.05,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
        keepOnSurface = "false";
        bounceOnSurface = 0.6;
        bounceOnSurfaceVar = 0;
        emissiveColor[] = {{ 1000,1000,1000,0 },{ 1,1,1,0 }};
    };
    class LaserSparks_small2: Default {
        interval = 0.001;
        //particleShape = "BH_SWIA_Weapons\Effects\ParticleEffects\Sparks\Sparkssmall2.p3d";
        particleShape = "\A3\data_f\ParticleEffects\Universal\smoke";
        particleFSNtieth = 1;
        particleFSIndex = 0;
        particleFSFrameCount = 1;
        particleFSLoop = 0;
        angle = 0;
        angleVar = 0;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.8;
        moveVelocity[] = {"surfNormalX * inSpeed / 250 * 5.66","surfNormalY * inSpeed / 250 * 5.66","surfNormalZ * inSpeed / 250 * 5.66"};
        rotationVelocity = 0;
        weight = 100;
        volume = 20;
        rubbing = 0;
        size[] = {0,0.015,0.015,0}; //size[] = {0,0.085,0.085,0};
        sizeCoef = 1;
        color[] = {{ 0.7,0.7,0.7,-10 }};
        colorCoef[] = {1,1,1,1};
        animationSpeed[] = {1};
        animationSpeedCoef = 1;
        randomDirectionPeriod = 10;
        randomDirectionIntensity = 1;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 0.2;
        positionVar[] = {0,0,0};
        moveVelocityVar[] = {1.5,1,1.5};
        rotationVelocityVar = 0;
        sizeVar = 0.15;
        colorVar[] = {0.05,0.05,0.05,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
        keepOnSurface = "false";
        bounceOnSurface = 0.6;
        bounceOnSurfaceVar = 0;
        emissiveColor[] = {{ 1000,1000,1000,0 },{ 1,1,1,0 }};
    };
    class ImpactSparksSabot007: Default {
        interval = 0.02;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        //particleShape = "\A3\data_f\ParticleEffects\Universal\SparksBall.p3d";
        particleShape = "\A3\data_f\ParticleEffects\Universal\SparksBall";
        particleFSNtieth = 1;
        particleFSIndex = 0;
        particleFSFrameCount = 1;
        particleFSLoop = 0;
        angleVar = 0;
        animationName = "";
        particleType = "SpaceObject";
        timerPeriod = 3;
        lifeTime = 0.005;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 0;
        weight = 1.275;
        volume = 1;
        rubbing = 0;
        size[] = {2.2};
        sizeCoef = 1;
        color[] = {{ 1,1,1,-50 }};
        colorCoef[] = {1,1,1,1};
        animationSpeed[] = {1000};
        animationSpeedCoef = 1;
        randomDirectionPeriod = 0;
        randomDirectionIntensity = 0;
        onTimerScript = "";
        beforeDestroyScript = "";
        blockAIVisibility = 0;
        lifeTimeVar = 0;
        position[] = {0,0,0};
        positionVar[] = {0,0,0};
        moveVelocityVar[] = {0,0,0};
        rotationVelocityVar = 0;
        sizeVar = 0.03;
        colorVar[] = {0.05,0.05,0.05,5};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
        emissiveColor[] = {{ 1000,1000,1000,0 },{ 1,1,1,0 }};
    };
    class ImpactSparks123: Default {
        interval = 0.015;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 13;
        particleFSFrameCount = 2;
        particleFSLoop = 0;
        angleVar = 360;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 3;
        lifeTime = 0.08;
        moveVelocity[] = {"(- inDirX * 2 + surfNormalX / 2) * inSpeed / 100","( - inDirY * 2 + surfNormalY / 2) * inSpeed / 100","( - inDirZ * 2 + surfNormalZ / 2) * inSpeed / 100"};
        rotationVelocity = 1;
        weight = 0.13;
        volume = 0.1;
        rubbing = 0;
        size[] = {0.016,0};
        sizeCoef = 1;
        color[] = {{ 1,1,1,-50 }};
        colorCoef[] = {1,1,1,1};
        animationSpeed[] = {1000};
        animationSpeedCoef = 1;
        randomDirectionPeriod = 0;
        randomDirectionIntensity = 0;
        onTimerScript = "";
        beforeDestroyScript = "";
        blockAIVisibility = 0;
        lifeTimeVar = 0.06;
        position[] = {0,0,0};
        positionVar[] = {0.01,0.01,0.01};
        moveVelocityVar[] = {5,5,5};
        rotationVelocityVar = 0;
        sizeVar = 0;
        colorVar[] = {0.05,0.05,0.05,5};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class LazerFlash2: Default {
        interval = 0.1;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 0;
        particleFSFrameCount = 32;
        particleFSLoop = 0;
        angleVar = 1;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 1;
        moveVelocity[] = {0,1,0};
        rotationVelocity = 1;
        weight = 10;
        volume = 7.9;
        rubbing = 0.1;
        size[] = {"0.0001","0.0001"};
        color[] = {{ 1,1,1,-1 },{ 1,1,1,0 }};
        animationSpeed[] = {2};
        randomDirectionPeriod = 0.2;
        randomDirectionIntensity = 0.2;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 0;
        positionVar[] = {0,0.1,0};
        MoveVelocityVar[] = {0.2,0.5,0.2};
        rotationVelocityVar = 1;
        sizeVar = 0.5;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    class LazerFlash: Default {
        interval = 0.01;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        //particleShape = "BH_SWIA_Weapons\Effects\ParticleEffects\Sparks\Explosion_10";
        particleShape = "\A3\data_f\ParticleEffects\Universal\Explosion_4x4";
        particleFSNtieth = 4;
        particleFSIndex = 0;
        particleFSFrameCount = 16;
        particleFSLoop = 0;
        angleVar = 360;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.5;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 1;
        weight = 0.045;
        volume = 0.04;
        rubbing = 0;
        size[] = {0.15};
        sizeCoef = 1.5;
        color[] = {{ 1,1,1,-200 },{ 1,1,1,-150 },{ 1,1,1,-20 },{ 1,1,1,-20 },{ 1,1,1,-20 },{ 1,1,1,-20 }};
        animationSpeed[] = {1};
        randomDirectionPeriod = 0.2;
        randomDirectionIntensity = 0.2;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 0;
        positionVar[] = {0,0,0};
        MoveVelocityVar[] = {0,0,0};
        rotationVelocityVar = 1;
        sizeVar = 0;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
        emissiveColor[] = {{ 1000,1000,1000,0 },{ 1000,1000,1000,0 }};
    };
    /*
    class LazerFlash: Default
    {
        interval = 0.15;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        particleShape = "BH_SWIA_Weapons\Effects\ParticleEffects\Sparks\Explosion_10";
        particleFSNtieth = 8;
        particleFSIndex = 0;
        particleFSFrameCount = 64;
        particleFSLoop = 0;
        angleVar = 360;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 1;
        moveVelocity[] = {0,0,0};
        rotationVelocity = 1;
        weight = 20;
        volume = 10;
        rubbing = 0;
        size[] = {0.1};
        sizeCoef = 1;
        color[] = {{ 1,1,1,-200 },{ 1,1,1,-150 },{ 1,1,1,-20 },{ 1,1,1,-20 },{ 1,1,1,-20 },{ 1,1,1,-20 }};
        animationSpeed[] = {1};
        randomDirectionPeriod = 0.2;
        randomDirectionIntensity = 0.2;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 0;
        positionVar[] = {0,0,0};
        MoveVelocityVar[] = {0,0,0};
        rotationVelocityVar = 1;
        sizeVar = 0;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0;
        randomDirectionIntensityVar = 0;
    };
    */
    class SmallLazerSmoke: Default {
        interval = 0.065;
        circleRadius = 0;
        circleVelocity[] = {0,0,0};
        particleShape = "\A3\data_f\ParticleEffects\Universal\Universal";
        particleFSNtieth = 16;
        particleFSIndex = 7;
        particleFSFrameCount = 48;
        particleFSLoop = 1;
        angleVar = 1;
        animationName = "";
        particleType = "Billboard";
        timerPeriod = 1;
        lifeTime = 0.5;
        moveVelocity[] = {0,0.8,0};
        rotationVelocity = 0;
        weight = 0.05;
        volume = 0.05;
        rubbing = 0.1;
        size[] = {0.15,1,1.5};
        sizeCoef = 1;
        color[] = {{ 0.1,0.1,0.1,0.75 },{ 0.2,0.2,0.2,0.4 },{ 0.2,0.2,0.2,0.2 },{ 0.3,0.3,0.3,0.1 },{ 0.4,0.4,0.4,0.02 }};
        colorCoef[] = {3,3,3,1.5};
        animationSpeed[] = {1.5,0.5};
        animationSpeedCoef = 1;
        randomDirectionPeriod = 0.4;
        randomDirectionIntensity = 0.02;
        onTimerScript = "";
        beforeDestroyScript = "";
        lifeTimeVar = 1.5;
        position[] = {0,0,0};
        positionVar[] = {0.08,0.04,0.08};
        MoveVelocityVar[] = {0.18,0.18,0.18};
        rotationVelocityVar = 10;
        sizeVar = 0.1;
        colorVar[] = {0,0,0,0};
        randomDirectionPeriodVar = 0.1;
        randomDirectionIntensityVar = 0.01;
    };
};
class CfgLights {
    class Light_RedLaser {
        color[] = {1,0,0.025,1};
        ambient[] = {0,0,0,0};
        brightness = 1;
        intensity = 4000;
        drawLight = 0;
        class Attenuation {
            start = 0;
            constant = 1;
            linear = 0;
            quadratic = 40;
        };
        position[] = {0,0.2,0};
        diffuse[] = {0.1,0,0.0025};
    };
};
class CfgAmmo {
    class BulletBase;
    class DMR_Laser_Ammo: BulletBase {
        hit = 14;
        indirectHit = 0.1;
        indirectHitRange = 0.2;
        explosive = 0.4;
        caliber = 5;
        cartridge = "";
        cost = 1;
        model = "\A3\Weapons_f\Data\bullettracer\tracer_red.p3d";
        tracerScale = 1.5;
        tracerStartTime = 0;
        tracerEndTime = 10;
        nvgOnly = 0;
        typicalSpeed = 60;
        visibleFire = 3;
        audibleFire = 5;
        visibleFireTime = 4;
        dangerRadiusBulletClose = 16;
        dangerRadiusHit = 40;
        suppressionRadiusBulletClose = 10;
        suppressionRadiusHit = 14;
        soundHit1[] = {PATHTOF(data\hit),1.9952624,1,120};
        soundHit2[] = {PATHTOF(data\hit),1.9952624,1,120};
        soundHit3[] = {PATHTOF(data\hit),1.9952624,1,120};
        soundHit4[] = {PATHTOF(data\hit),1.9952624,1,120};
        soundHit5[] = {PATHTOF(data\hit),1.9952624,1,120};
        soundHit6[] = {PATHTOF(data\hit),1.9952624,1,120};
        multiSoundHit[] = {"soundHit1",0.2,"soundHit2",0.2,"soundHit3",0.2,"soundHit4",0.1,"soundHit5",0.15,"soundHit6",0.15};
        explosionSoundEffect = "DefaultExplosion";
        airLock = 0;
        CraterEffects = "ExploAmmoLaserCrater";
        explosionEffects = "LaserExploSmall";
        effectFly = "RedLaserEffect";
        airFriction = 0;
        muzzleEffect = "";
        deflecting = 0;
        initTime = 0;
        gravityFactor = 0;
        coefGravity = 0;
        supersonicCrackNear[] = {};
        supersonicCrackFar[] = {};
        class SuperSonicCrack {
            superSonicCrack[] = {};
            class A {
                range[] = {0,10};
                sound[] = {};
                frequency = "((speed factor [330, 930]) * 0.1) + 1.05";
            };
            class B {
                range[] = {10,30};
                sound[] = {};
                frequency = "((speed factor [330, 930]) * 0.1) + 1.05";
            };
            class C {
                range[] = {30,500};
                sound[] = {};
                frequency = "((speed factor [330, 930]) * 0.1) + 1.05";
            };
        };
    };
};
class CfgMagazines {
    class 10Rnd_338_Mag;
    class XRnd_Laser_Mag: 10Rnd_338_Mag {
        scope = 1;
        scopeArsenal = 0;
        displayName = "Laser gun battery";
        descriptionShort = "Laser gun battery";
        ammo = "DMR_Laser_Ammo";
        tracersEvery = 1;
        type = 16;
        count = 10000;
        mass = 1;
        initSpeed = 310;
    };
};
class Mode_SemiAuto;
class CfgWeapons {
    //class DMR_02_base_F;
    //class srifle_DMR_02_F: DMR_02_base_F {};
    class srifle_DMR_02_F;
    class srifle_DMR_02_LaserGun_F: srifle_DMR_02_F {
        scope = 1;
        scopeArsenal = 0;
        author = "Bohemia Interactive";
        magazines[] = {"XRnd_Laser_Mag"};
        displayname = "Laser gun";
        descriptionShort = "Laser gun";
        soundBullet[] = {};
        modes[] = {"Single","close","short","medium","far"};
        selectionFireAnim = "zasleh";
        fireLightDuration = 0.05;
        fireLightIntensity = 0.2;
        fireLightDiffuse[] = {0.1,0,0.0025};
        fireLightAmbient[] = {0,0,0};
        inertia = 0.3;
        dexterity = 1.7;
        initSpeed = 400;
        cursor = "EmptyCursor";
		cursorAim = "mg";
        class LinkedItems {
            class LinkedItemsOptic {
                item = "optic_Nightstalker";
                slot = "CowsSlot";
            };
        };
        class WeaponSlotsInfo {
            allowedSlots[] = {};
            mass = 180;
            class CowsSlot {
                access = 0;
                displayName = "Optics Slot";
                iconPicture = "\A3\Weapons_F\Data\UI\attachment_top";
                iconPinpoint = "Bottom";
                iconPosition[] = {0.5,0.36};
                iconScale = 0.2;
                linkProxy = "\A3\data_f\proxies\weapon_slots\TOP";
                scope = 0;
                class compatibleItems {
                    optic_Nightstalker = 1;
                };
            };
        };
        class Single: Mode_SemiAuto {
            sounds[] = {"StandardSound"};
            class BaseSoundModeType {
                weaponSoundEffect = "DefaultDMRLaser";
                closure1[] = {};
                closure2[] = {};
                soundClosure[] = {};
            };
            class StandardSound: BaseSoundModeType {
                weaponSoundEffect = "DefaultDMRLaser";
                begin1[] = {PATHTOF(data\laser),1.1220185,1,1100};
                soundBegin[] = {"begin1",1};
                closure1[] = {};
                soundClosure[] = {"closure1",0.5};
            };
            reloadTime = 0.3;
			dispersion = 0;
			soundContinuous = 0;
			soundBurst = 0;
			showToPlayer = 1;
			burst = 1;
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 50;
			minRange = 1;
			minRangeProbab = 0.01;
			midRange = 2;
			midRangeProbab = 0.01;
			maxRange = 3;
			maxRangeProbab = 0.01;
			textureType = "fullAuto";
        };
        class close: Single
		{
			showToPlayer = 0;
			burst = 15;
			aiRateOfFire = 0.25;
			aiRateOfFireDistance = 400;
			minRange = 0;
			minRangeProbab = 0.05;
			midRange = 200;
			midRangeProbab = 0.7;
			maxRange = 400;
			maxRangeProbab = 0.2;
		};
		class short: close
		{
			burst = 10;
			aiRateOfFire = 0.5;
			aiRateOfFireDistance = 500;
			minRange = 300;
			minRangeProbab = 0.2;
			midRange = 400;
			midRangeProbab = 0.7;
			maxRange = 500;
			maxRangeProbab = 0.2;
		};
		class medium: close
		{
			burst = 7;
			aiRateOfFire = 1;
			aiRateOfFireDistance = 900;
			minRange = 400;
			minRangeProbab = 0.2;
			midRange = 700;
			midRangeProbab = 0.7;
			maxRange = 900;
			maxRangeProbab = 0.2;
		};
		class far: close
		{
			burst = 4;
			aiRateOfFire = 1.5;
			aiRateOfFireDistance = 1500;
			minRange = 800;
			minRangeProbab = 0.2;
			midRange = 1000;
			midRangeProbab = 0.4;
			maxRange = 1500;
			maxRangeProbab = 0.01;
		};
    };
};
