#define COMPONENT dialogue
#define COMPONENT_BEAUTIFIED Dialogue
#include "\z\a3cs\addons\main\script_mod.hpp"

#define DEBUG_MODE_FULL
// #define DISABLE_COMPILE_CACHE
// #define ENABLE_PERFORMANCE_COUNTERS

#include "\z\a3cs\addons\main\script_macros.hpp"

#define IDC_DIALOGUE_UI_BG 1780
#define IDC_DIALOGUE_UI_TITLE 4700
#define IDC_DIALOGUE_UI_TEXTCTRLGRP 4701
#define IDC_DIALOGUE_UI_TEXT 4702
#define IDC_DIALOGUE_UI_LISTOPTIONS_LABEL 4703
#define IDC_DIALOGUE_UI_LISTOPTIONS 4704
#define IDC_DIALOGUE_UI_CONFIRM_LABEL 4705
#define IDC_DIALOGUE_UI_CONFIRM_BTN 4706
#define IDC_DIALOGUE_UI_CANCEL_BTN 4707
