//modules
PREP(module_cacheSettings);
PREP(module_genSoldiers);
PREP(module_genAttack);
PREP(module_surrenderUnit);
PREP(module_handcuffUnit);
PREP(module_hideTerrainObjects);
PREP(module_colorCorrections);
PREP(module_playSound);
PREP(module_missionIntro);
PREP(module_genMinefield);
PREP(module_fireArtillery);
//PREP(module_genCAS);
PREP(module_createTask);
PREP(module_setTaskState);
PREP(module_sandStorm);
PREP(module_fogEffect);
PREP(module_snowEffect);
PREP(module_breathFog);
PREP(module_lanterns);

//other
PREP(initHeadless);
PREP(initCache);
PREP(cacheGroup);
PREP(uncacheGroup);
PREP(cacheGroupHandler);
PREP(cacheModulesHandler);
PREP(setSkillLevel);
PREP(disableGroupAI);
PREP(enableGroupAI);
PREP(genSoldiers_callSupport);
PREP(genSoldiers_handleKilled);
PREP(genAttack_handleKilled);
PREP(genAttack_genUnits);
PREP(setColorCorrection);
PREP(fireArtillery_fireShell);
PREP(createTask);
PREP(setTaskState);
PREP(sandStorm);
PREP(fogEffect);
PREP(snowEffect);
PREP(breathFog);
PREP(playSound3D);

PREP(checkUnconsciousness);

PREP(handleInitPost);
PREP(handleKilled);
PREP(handleLocal);
PREP(transferGroups);

PREP(loadUnitSettings);
PREP(onLoadIntroEffect);
PREP(canExecuteModule);
PREP(setDisposable);
