class CfgDifficultyPresets {
    defaultPreset = "Veteran";
    class Recruit {
        levelAI = "AILevelHigh";
        displayName = "A3C + 3 osoba";
        class Options {
            reducedDamage = 0;
            groupIndicators = 0;
            friendlyTags = 0;
            enemyTags = 0;
            detectedMines = 0;
            commands = 1;
            waypoints = 0;
            weaponInfo = 1;
            stanceIndicator = 1;
            staminaBar = 0;
            weaponCrosshair = 0;
            visionAid = 0;
            thirdPersonView = 1;
            cameraShake = 1;
            scoreTable = 1;
            deathMessages = 0;
            vonID = 0;
            mapContent = 0;
            autoReport = 0;
            multipleSaves = 0;
        };
    };
    class Regular {
        displayName = "A3C";
        levelAI = "AILevelHigh";
        class Options {
            reducedDamage = 0;
            groupIndicators = 0;
            friendlyTags = 0;
            enemyTags = 0;
            detectedMines = 0;
            commands = 1;
            waypoints = 0;
            weaponInfo = 1;
            stanceIndicator = 1;
            staminaBar = 0;
            weaponCrosshair = 0;
            visionAid = 0;
            thirdPersonView = 0;
            cameraShake = 1;
            scoreTable = 0;
            deathMessages = 0;
            vonID = 0;
            mapContent = 0;
            autoReport = 0;
            multipleSaves = 0;
        };
    };
    class Veteran {
        displayName = "A3C";
        levelAI = "AILevelHigh";
        class Options {
            reducedDamage = 0;
            groupIndicators = 0;
            friendlyTags = 0;
            enemyTags = 0;
            detectedMines = 0;
            commands = 1;
            waypoints = 0;
            weaponInfo = 1;
            stanceIndicator = 1;
            staminaBar = 0;
            weaponCrosshair = 0;
            visionAid = 0;
            thirdPersonView = 0;
            cameraShake = 1;
            scoreTable = 0;
            deathMessages = 0;
            vonID = 0;
            mapContent = 0;
            autoReport = 0;
            multipleSaves = 0;
        };
    };
};
