import os

VENDOR = {
    "@ACE": {
        "blacklist": [
            "ace_advanced_fatigue",
            "ace_hearing",
            "ace_nametags",
            "ace_sandbag",
            "ace_volume",
            "ace_viewrestriction",
            "ace_headless",
            "ace_killtracker"
        ],
        "optionals": [
            os.path.join("@ace_nocrosshair", "addons", "ace_nocrosshair.pbo"),
            os.path.join("@ace_nouniformrestrictions", "addons", "ace_nouniformrestrictions.pbo"),
        ],
    },
    "@LAMBS_Danger.fsm": {},
    "@LAMBS_Suppression": {},
    "@LAMBS_Turrets": {},
    "@LAMBS_RPG": {},
    "@3den Enhanced": {},
    "@Blurry Laser": {},
    "@Ladder Tweak": {},
    "@Zeus Enhanced": {},
    "@Zeus Enhanced - ACE3 Compatibility": {},
    "@Enhanced Movement": {},
    "@Enhanced Movement Rework": {},
    "@Gruppe Adler Trenches": {},
    "@VET_Unflipping": {},
    "@BackpackOnChest - Redux": {},
    "@Breaching Charge": {},
    "@Eden Extended Objects": {},
    "@O&T Expansion Eden": {
        "blacklist": ["expEden_static_ssDM"],
    },
    "@Metis Nature": {},
    "@vurtual's Car Seat & Stretcher": {},
    "@Vurtual's Ships": {},
    "@PLP Markers": {},
    "@PLP Containers": {},
    "@PLP Beach Objects": {},
    "@PLP Urban Packs- Barriers and Fences": {},
    "@PLP Urban Packs- Private Property": {},
    "@Extended Fortifications Mod": {},
    "@AVON FM12 Respirator Pack": {},
    "@Blastcore Murr Edition": {},
    "@Modular Buildings - Laboratory": {},
    "@Swim Faster": {},
    "@L3-GPNVG18 Panoramic Night Vision": {},
    "@PMK-1 Gas mask": {},
    "@M40 protective mask": {},
    "@Hate's Hidden Cameras": {},
    "@ArmaZeusCache": {},
    "@ILBE Assault Pack - Rewrite": {},
    "@FRXA's TFAR Extra Retextured Equipment": {},
    "@ACD - Arma3 Containers And Decorations": {},
    "@Uriki's Mission Items": {},
    "@Ragdoll Physics Plus+ v1.12": {},
    "@Enhanced Map Ace Version": {},
    "@Improved Melee System": {},
    "@Simple Armbands": {},
    "@MS_IFF_Strobe": {},
    "@Rismarck's Static Animations": {},
    "@ZSL Static Poses [WW2]": {},
    "-JSHK_Contamination_Gear": {},
    "-A3CS_vendor": {},
}
