/*
 * Author: SzwedzikPL
 * Man killed EH handler
 */
#include "script_component.hpp"

params ["_unit"];
if (!local _unit) exitWith {};

//remove dummy vest if present
if(vest _unit == "a3cs_dummyVest") then {removeVest _unit;};

//if generated by mm modules call proper handler
if(_unit getVariable ["a3cs_generated", false]) then {
    if(_unit getVariable [QGVAR(genSoldiers), false]) then {
        [_unit] call FUNC(genSoldiers_handleKilled);
    };
    if(_unit getVariable [QGVAR(genAttack), false]) then {
        [_unit] call FUNC(genAttack_handleKilled);
    };
};
