#include "\a3\3DEN\UI\resincl.inc"

// Control IDC
#define IDC_DISPLAY3DEN_PANELLEFT_WARNINGS        1200
#define IDC_DISPLAY3DEN_PANELLEFT_WARNINGS_ICON   1201
#define IDC_DISPLAY3DEN_PANELLEFT_WARNINGS_INFO   1202
#define IDC_DISPLAY3DEN_PANELLEFT_WARNINGS_TREE   1203
