PREP(addActionToClass);
PREP(addActionToObject);
PREP(addMainAction);
PREP(compileMenu);
PREP(compileMenuSelfAction);
PREP(compileMenuZeus);
PREP(collectActiveActionTree);
PREP(createAction);
PREP(ctrlSetParsedTextCached);
PREP(findActionNode);
PREP(handlePlayerChanged);
PREP(isSubPath);
DFUNC(keyDown) = compileFinal preProcessFileLineNumbers "\z\a3cs\addons\interact_menu\functions\fnc_keyDown.sqf";//PREP(keyDown);
DFUNC(keyUp) = compileFinal preProcessFileLineNumbers "\z\a3cs\addons\interact_menu\functions\fnc_keyUp.sqf";//PREP(keyUp);
PREP(removeActionFromClass);
PREP(removeActionFromObject);
PREP(render);
DFUNC(renderActionPoints) = compileFinal preProcessFileLineNumbers "\z\a3cs\addons\interact_menu\functions\fnc_renderActionPoints.sqf";//PREP(renderActionPoints);
DFUNC(renderBaseMenu) = compileFinal preProcessFileLineNumbers "\z\a3cs\addons\interact_menu\functions\fnc_renderBaseMenu.sqf";//PREP(renderBaseMenu);
PREP(renderIcon);
DFUNC(renderMenu) = compileFinal preProcessFileLineNumbers "\z\a3cs\addons\interact_menu\functions\fnc_renderMenu.sqf";//PREP(renderMenu);
PREP(renderSelector);
PREP(setupTextColors);
PREP(splitPath);
PREP(userActions_addHouseActions);
PREP(userActions_getHouseActions);
